spring:
  application:
    name: zipkin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/, http://localhost:7004/eureka/, http://localhost:7005/eureka/

server:
  port: 8004
