spring:
  application:
    name: customer2

server:
  port: 6004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/, http://localhost:7004/eureka/, http://localhost:7005/eureka/

feign:
  hystrix:
    enabled: true