version: '3'
services:
  eureka-server-cluster3:
      image: tjffy/eureka-server-cluster:0.0.1-SNAPSHOT
      ports:
        - "7003:7003"
      container_name: eureka-server-cluster3
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=peer3", "-jar", "/app.jar"]
  eureka-server-cluster4:
      image: tjffy/eureka-server-cluster:0.0.1-SNAPSHOT
      ports:
        - "7004:7004"
      container_name: eureka-server-cluster4
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=peer4", "-jar", "/app.jar"]
  eureka-server-cluster5:
      image: tjffy/eureka-server-cluster:0.0.1-SNAPSHOT
      ports:
        - "7005:7005"
      container_name: eureka-server-cluster5
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=peer5", "-jar", "/app.jar"]
  zuul1:
      image: tjffy/zuul:0.0.1-SNAPSHOT
      ports:
        - "8002:8002"
      container_name: zuul1
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=zuul1", "-jar", "/app.jar"]
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=zuul2", "-jar", "/app.jar"]
  zuul2:
      image: tjffy/zuul:0.0.1-SNAPSHOT
      ports:
        - "8003:8003"
      container_name: zuul2
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=zuul2", "-jar", "/app.jar"]
      links:
        - zipkin
  producer:
      image: tjffy/producer:0.0.1-SNAPSHOT
      ports:
        - "6003:6003"
      container_name: producer2
      volumes:
         - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=local2", "-jar", "/app.jar"]
      links:
         - zipkin
  customer:
      image: tjffy/customer:0.0.1-SNAPSHOT
      ports:
        - "6004:6004"
      container_name: customer2
      volumes:
         - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=customer2", "-jar", "/app.jar"]
  zipkin:
      image: tjffy/zipkin:0.0.1-SNAPSHOT
      ports:
        - "8004:8004"
      container_name: zipkin
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
  dashboard:
      image: tjffy/dashboard:0.0.1-SNAPSHOT
      ports:
        - "6005:6005"
      container_name: dashboard
      volumes:
         - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]