spring:
  application:
    name: zuul2

server:
  port: 8003

zuul:
  routes:
    tjffy-p1:
      path: /procuder1/**
      url: http://localhost:6001/
    tjffy-p2:
      path: /procuder2/**
      url: http://localhost:6003/
    tjffy-c1:
      path: /customer2/**
      serviceId: customer2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/, http://localhost:7004/eureka/, http://localhost:7005/eureka/
