spring:
  application:
    name: zuul1

server:
  port: 8002

zuul:
# 是否开启重试功能
  retryable: true
#  routes:
#    tjffy-p1:
#      path: /procuder1/**
#      url: http://localhost:6001/
#    tjffy-p2:
#      path: /procuder2/**
#      url: http://localhost:6003/
#    tjffy-c1:
#      path: /customer2/**
#      serviceId: customer2
#  禁用zuul指定的filter
#  FormBodyWrapperFilter:
#    pre:
#      disable: true
#    routing:
#      disable: true
#    post:
#      disable: true
#    error:
#      disable: true

ribbon:
# 对当前服务的重试次数
  MaxAutoRetries: 2
# 切换相同Server的次数
  MaxAutoRetriesNextServer: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/, http://localhost:7004/eureka/, http://localhost:7005/eureka/
